# Generated by Django 5.0.3 on 2024-03-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('task', '0007_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'verbose_name_plural': 'Task History'},
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.category'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='title',
            field=models.CharField(default='Task', max_length=255),
        ),
    ]
